[advisories]
yanked = "deny"

[bans]
multiple-versions = "warn"
multiple-versions-include-dev = true
wildcards = "deny"
highlight = "all"

[licenses]
confidence-threshold = 0.93
include-dev = true
allow = [
    "0BSD",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "Unicode-3.0",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
