const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const state = vm.createContext({});
vm.runInContext(fs.readFileSync(__dirname + '/../ChatState.js', 'utf8'), state);
const key = 'a'.repeat(64), other = 'b'.repeat(64);
let s = state.create();
state.snapshot(s, {status: {dm_relay_count:1}, messages: []});
state.select(s, 'dm:' + key);
state.current(s).draft = 'hello';
const first = state.beginSend(s);
assert(first);
assert.equal(state.beginSend(s), null, 'double send blocked');
state.select(s, 'dm:' + other);
state.current(s).draft = 'different draft';
state.response(s, {id:first.id, ok:true, data:{id:'1', delivery:'stored'}});
assert.equal(state.current(s).draft, 'different draft', 'late response never clears another chat');
assert.equal(s.chats[0].draft, '');
state.event(s, {topic:'messages', payload:{id:'1',conversation:'dm:'+key,text:'hello',delivery:'stored',outgoing:true}}, true);
assert.equal(s.chats[0].messages.length, 1, 'send response/event deduplication');
state.current(s).draft = '😀'.repeat(1025);
assert.equal(state.beginSend(s), null, 'UTF-8 byte limit');
state.current(s).draft = 'keep this';
const pending = state.beginSend(s);
state.disconnected(s, 'lost');
assert.equal(state.current(s).draft, 'keep this');
assert.equal(state.current(s).uncertain, true);
state.snapshot(s, {status:{dm_relay_count:1},messages:[]});
assert.equal(state.beginSend(s), null, 'unknown sends cannot auto-retry after reconnect');
state.current(s).uncertain = false;
const rejected = state.beginSend(s);
state.response(s, {id:rejected.id,ok:false,error:'relay refused'});
assert.equal(state.current(s).draft,'keep this');
assert.equal(state.current(s).error,'relay refused');
const slow = state.beginSend(s);
state.response(s, {id:slow.id, ok:false, unknown:true, error:'no answer'});
assert.equal(state.current(s).draft,'keep this', 'unknown outcome keeps the draft');
assert.equal(state.current(s).uncertain, true, 'unknown outcome blocks resending');
assert.equal(state.beginSend(s), null);
state.current(s).uncertain = false;
state.event(s,{topic:'messages',payload:{id:'in',conversation:'dm:'+other,text:'<img src=x>',delivery:'received'}},false);
assert.equal(state.current(s).unread,1, 'inactive window retains unread indication');
state.event(s,{topic:'messages',payload:{id:'in',conversation:'dm:'+other,text:'duplicate',delivery:'received'}},false);
assert.equal(state.current(s).unread,1);
state.event(s,{topic:'messages',payload:{id:'in',conversation:'dm:'+other,deleted:true}},true);
assert.equal(state.current(s).messages.length,0);
assert.equal(state.dmKey('dm:'+key.toUpperCase()),key);
assert.equal(state.dmKey('javascript:alert(1)'), '');
assert.equal(state.deliveryLabel('stored'),'Stored by relay');
for(let i=0;i<200;i++) state.applyMessage(s,{id:'m'+i,conversation:'dm:'+other,text:'bounded',delivery:'received'},true,true);
assert.equal(state.current(s).messages.length,128);
state.current(s).draft = 'do not send through a legacy profile';
s.status.dm_relay_count = 0;
assert.equal(state.beginSend(s),null);
s.status.nostr_public_key = key;
state.snapshot(s,{status:{nostr_public_key:other,dm_relay_count:1},messages:[]});
assert.equal(s.chats.length,0,'new daemon identity must not inherit old plaintext/drafts');
for(let i=0;i<128;i++) state.ensure(s,'chat-'+i);
state.select(s,'chat-0');
assert.equal(state.select(s,'new-chat'),false,'a refused open must not focus the previous recipient as if successful');
assert.equal(s.active,'chat-0');
console.log('PASS: draft ownership, duplicate suppression, UTF-8 limits, unknown/rejected sends, unread, deletion and bounds');
