complete -c omachat-ctl -l socket -r -d 'Daemon socket path'
complete -c omachat-ctl -n '__fish_use_subcommand' -a 'status fingerprint send hosted-conversations hosted-history hosted-mark-read hosted-open-dm hosted-claim-handle hosted-resolve-handle hosted-create-workspace hosted-create-channel hosted-add-member panic'
complete -c omachat-ctl -n '__fish_seen_subcommand_from status' -l json -d 'Emit compact JSON'
complete -c omachat-ctl -n '__fish_seen_subcommand_from fingerprint' -l qr -d 'Render ANSI QR code'
complete -c omachat-ctl -n '__fish_seen_subcommand_from panic' -l confirm -a ERASE -d 'Confirm destructive erase'
complete -c omachat-ctl -n '__fish_seen_subcommand_from hosted-conversations' -l json -d 'Emit compact JSON'
complete -c omachat-ctl -n '__fish_seen_subcommand_from hosted-open-dm' -l json -d 'Emit compact JSON'
complete -c omachat-ctl -n '__fish_seen_subcommand_from hosted-resolve-handle' -l json -d 'Emit compact JSON'
complete -c omachat-ctl -n '__fish_seen_subcommand_from hosted-history' -l before -r -d 'Page before this sequence'
complete -c omachat-ctl -n '__fish_seen_subcommand_from hosted-history' -l limit -r -d 'Messages per page'
complete -c omachat-ctl -n '__fish_seen_subcommand_from hosted-history' -l json -d 'Emit compact JSON'
